README.md
#What
最終課題フリマアプリデータベース設計です。
#Why
フリマアプリ開発に向けてDBは基礎となるため
※以前は別の方がレビューをしておりました。以前のものは下記のURLより確認できます
https://github.com/Kensuke-Mitsui/freemarket_sample_74b/pull/5
=> freemarket DB設計　teamb

app/assets/stylesheets/application.scss, app/assets/stylesheets/items/_index.scss, app/assets/stylesheets/orders/_index.scss
#what
orders/indexの記述がフッターとヘッダーに競合している部分をコメントアウト。
#why
共通部分に、ビュー崩れが起きているから
=> 一旦須藤さんの記述をコメントアウトしました。

app/assets/stylesheets/application.scss, app/assets/stylesheets/items/_new.scss, app/views/items/new.html.haml
マークアップ(商品出品ページ)
①app/views/items/new.html.haml：作成かつ記述
②app/asets/stylesheets/items/_new.scss：作成かつ記述
③application.scss：_new.scssを読み込むための記述を追加
本アプリケーションにおける必須機能のため
https://gyazo.com/d7179f632c520867ec1540bbc66eae62
=> マークアップ商品出品ページ

app/assets/stylesheets/items/_index.scss
#what
本番でも画像が見えるように記述を変更
#why
本番環境で画像が表示されていなかったから
=> 本番でも画像が見えるように記述を変更

app/controllers/items_controller.rb, app/views/items/index.html.haml, app/views/layouts/compact.html.haml, config/routes.rb
#what
ヘッダー部分をcompactに格納し、items/index、showだけに記述した
#why
ヘッダーが要らないページもあるから
=> indexとshow以外ではフッターを表示させないようにしました

db/migrate/20200507060555_create_users.rb, db/migrate/20200508061628_create_items.rb
#what
レードミーの内容をマイグレーションファイルに記載
#why
不要な記載を一旦なくすため
=> マイグレーションファイルの記述を直しました

.gitignore, db/migrate/20200507060555_create_users.rb, db/migrate/20200507060721_create_credit_cards.rb
DB設計の見直しを行い、一部のmigrateの修正が必要となったため
・users→済（masterには反映済。）
・items→済
・images→済
・credit_card→今回のプルリクエスト対象
クレジットカード情報についてはpayjpにて情報を保管するため、個人情報に該当するカラムを削除。payjpから情報を取得するカラムを追加
チーム内レビューでOKであればマージをお願いします。
=> credit_card migrate修正

Gemfile, Gemfile.lock, app/assets/javascripts/items_category.js, app/controllers/items_controller.rb, app/models/category.rb, app/models/item.rb, app/views/items/_form.html.haml, app/views/items/set_children.json.jbuilder, app/views/items/set_grandchildren.json.jbuilder, app/views/items/set_parents.json.jbuilder, config/routes.rb, db/migrate/20200508061628_create_items.rb, db/schema.rb
#what
Gemfile gem 'jquery-turbolinks' 　ターボリンクスが邪魔して、ページ切り替えの時にできなかったり→解消
app/assets/javascripts/items_category.js　セレクトタブを動的に増やします
app/controllers/items_controller.rb　記述ミスを修正
app/models/category.rb　アソシエーションを組む
app/models/item.rb　アソシエーションを組む
app/views/items/_form.html.haml　セレクトタグはjqueryで増やすので要らない
db/migrate/20200508061628_create_items.rb　紐付けをするため　_idを付けました。
#why
出品時にカテゴリーと紐付けするため
=> カテゴリー登録機能追加

app/assets/javascripts/items.js
・「商品出品機能の動的フォームがリロードしないと使えない問題」の解消
https://gyazo.com/f833c3531c84d4d945ff8efe7be638ad
本アプリケーションの根幹機能のため
①『% git pull upstream master』で最新のmasterの状態を反映させた
②「jQueryが上手く動かない問題の解消」のため、本ブランチを切った
③『% bundle install』
④『% rake db:drop』
④『% rails db:create』
⑤『% rails db:migrate』
⑥「商品出品機能の動的フォームがリロードしないと使えない問題」は解消
app/assets/javascripts/items.js
該当のjqueryの記述を
『$(document).on('turbolinks:load',(function(){　}))』
の記述の中に入れることで解消できた
https://qiita.com/ohnitakahiro/items/d9839cf24a4eee2394ac
=> jQueryが上手く動かない問題の解消

app/assets/stylesheets/_color.scss, app/assets/stylesheets/orders/_index.scss
商品購入画面のエラー解消のため
商品購入の機能実装を行うにあたり、画面が正常にするために取り急ぎマージを行いたいと思います。
・$theme-colorを指定していなかったことによるエラーを解消
・その他、colorを変更しました
=> 商品購入画面のエラー解消

app/controllers/items_controller.rb, app/views/items/create.html.haml, app/views/items/show.html.haml
#what
before_actionの記述を変更
その他エラー
エラー解消のため
=> 出品可能、商品詳細見れるようにしました

app/assets/javascripts/items_category.js, app/assets/stylesheets/items/_show.scss, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/show.html.haml
#what
app/assets/javascripts/items_category.js　起動条件の修正
app/controllers/items_controller.rb　itemsをビフォーアクションでセット
app/models/item.rb　不要な記述なので削除
app/views/items/show.html.haml　ボタン設置
#why
編集　削除をするため
https://gyazo.com/254658179624a3164dd6928bbcc5bb95
=> 商品削除機能、編集ボタン実装

app/assets/stylesheets/application.scss, app/assets/stylesheets/items/_create.scss, app/assets/stylesheets/items/_new.scss, app/models/item.rb, app/views/items/create.html.haml
商品出品完了ページ（app/views/items/create.html.haml）最低限のマークアップ
https://gyazo.com/811da4c33af0103e95b1561329af4fb1
必要な画面なので
app/views/items/create.html.haml
　空だった中身を記述
　商品出品、商品詳細、ホームへのリンクも記述
app/assets/stylesheets/items/_create.scss
　作成、および記述
　
app/assets/stylesheets/application.scss
　@import "items/create";
app/models/item.rb
　少し見やすく整えた
　コメントアウトしているが、バリデーションをイメージとして記述してみた
=> 【マークアップ】商品出品完了ページ（app/views/items/create.html.haml）

config/environments/production.rb
デプロイ解消のための作業
デプロイ時にエラーが発生しているため、想定されるコードをコメントアウトした
参考URL：https://qiita.com/mikd/items/e10805343f2d7534d52c
=> デプロイ解消のための作業

app/models/image.rb, app/models/item.rb, db/schema.rb
◼︎画像が0枚の時に出品できないようになっている
◼︎「必須」と表現してあるカラム（brand以外）が空のときに出品ができない
◼︎「必須」と表現していないカラム（brand）が空のときには出品ができる
◼︎価格が「¥300〜9,999,999」でないと出品できない
本アプリケーションの必須機能の実装のため
=> 商品出品機能(バリデーションをかける)

app/assets/stylesheets/registrations/_new.scss, app/views/devise/registrations/new.html.haml
＃what
・.envファイルの追加
　.envファイルを追加してキーを保存
・birthdayカラムの追加とバリデーション付与
＃why
payjpと新規登録機能で必須なため
=> envファイル修正とbirthdayカラムの修正

app/assets/stylesheets/application.scss, app/assets/stylesheets/registrations/_show_address.scss, app/controllers/users/registrations_controller.rb, app/views/devise/registrations/show.html.haml, app/views/devise/registrations/show_address.html.haml, app/views/layouts/compact.html.haml, config/routes.rb
#what
マイページにてaddressモデル情報表示
show_address.html.hamlを大まかにいじったので確認いただけると幸いです。
#59 why
住所が登録されているかを確認できるようにするため
=> マイページへ住所の表示

app/assets/javascripts/payjp.js
javascriptの処理速度を上げるためにturbolinksを導入
処理速度を上げるため
=> turbolinks処理

app/assets/stylesheets/items/_index.scss, app/controllers/items_controller.rb, app/controllers/orders_controller.rb, app/models/item.rb, app/views/items/_item.html.haml, db/migrate/20200507060555_add_devise_to_users.rb, db/migrate/20200516050558_create_addresses.rb
編集画面のエラーハンドリング を表示
必須項目の未入力の場合、該当項目を表示させる
下記のエラーを修正
・マイグレート時に発生するシンタックスエラーを解消【ユーザー登録時のマイグレーション修正】
・商品出品時の最低金額300円に修正【商品出品金額_300円以上に修正】
・未購入商品も購入済みになっていたため修正【購入済商品の修正】
・購入済み商品の表示【商品一覧_購入済みを記載】
=> エラーハンドリング  編集機能

app/views/devise/registrations/show.html.haml
#what
マイページログアウトボタン修正
#why
ログアウトできなかったため
=> マイページログイン機能修正

app/views/items/_form.html.haml
=> 出品エラーメッセージ修正

app/models/address.rb, db/migrate/20200516050558_create_addresses.rb, db/schema.rb
#what
phone_numberカラム　バリデーション修正
#why
空欄の場合でも登録できるようにするため
=> phone_number修正

app/models/user.rb, app/views/devise/registrations/new.html.haml
#what
確認ようパスワードの追加
#why
セキュリティ性向上のため
=> 新規登録パスワード確認様フォームのついか
